// ─── Filter Parameter Types ───────────────────────────────────────────────────
// Each param type maps directly to a UI control generated by FilterPanel.

export interface SliderParam {
  type: 'slider';
  id: string;
  label: string;
  min: number;
  max: number;
  step: number;
  default: number;
  group?: string;
}

export interface ToggleParam {
  type: 'toggle';
  id: string;
  label: string;
  default: boolean;
  group?: string;
}

export interface ColorParam {
  type: 'color';
  id: string;
  label: string;
  /** Hex string e.g. "#00ff00" */
  default: string;
  group?: string;
}

export interface SelectParam {
  type: 'select';
  id: string;
  label: string;
  options: { value: string | number; label: string }[];
  default: string | number;
  group?: string;
}

export type FilterParam = SliderParam | ToggleParam | ColorParam | SelectParam;

// ─── Texture Uniforms ─────────────────────────────────────────────────────────
// Allows filters to declare sampler2D uniforms backed by image files.
// The FilterRegistry loads these images and passes them as Three.js textures.

export interface TextureUniform {
  /** Name of the sampler2D uniform in the fragment shader */
  uniformName: string;
  /** File path relative to the filter's definition folder */
  file: string;
  wrapS?: 'repeat' | 'clamp';
  wrapT?: 'repeat' | 'clamp';
}

// ─── Additional Render Passes ─────────────────────────────────────────────────
// Stub for multi-pass effects (e.g. watercolour fluid sim). The EffectComposer
// chains these after the primary ShaderPass.

export interface AdditionalPass {
  vertexShader: string;
  fragmentShader: string;
}

// ─── Param Groups ─────────────────────────────────────────────────────────────

export interface ParamGroup {
  id: string;
  label: string;
  collapsed?: boolean;
}

// ─── Filter Definition ────────────────────────────────────────────────────────

export interface FilterDefinition {
  id: string;
  name: string;
  description?: string;
  vertexShader: string;
  fragmentShader: string;
  params: FilterParam[];
  /**
   * Optional texture uniforms. Empty / absent means no extra textures.
   * FilterRegistry resolves file paths relative to the filter folder and
   * creates Three.js Texture objects, passed as uniforms to the shader.
   */
  textures?: TextureUniform[];
  /**
   * Optional chained ShaderPasses added after the primary pass.
   * Stub field — ignored until multi-pass support is implemented.
   */
  additionalPasses?: AdditionalPass[];
  /** Collapsible groups for params. Ungrouped params appear at the top. */
  groups?: ParamGroup[];
  /**
   * Set true for filters that use the `time` uniform for visible animation
   * (scanlines, flicker, CRT effects, etc.).  The renderer runs at full 60 fps
   * for animated filters and renders once-per-change for static filters.
   * Defaults to false (static) when absent.
   */
  animated?: boolean;
}

// ─── Resolved uniform value types used at runtime ────────────────────────────

export type UniformValue = number | boolean | string | THREE_Texture;

// We import the Three.js Texture type lazily to avoid a hard dep here.
// At runtime the actual three.Texture objects are passed through.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type THREE_Texture = any;

// Saved values for a filter's params, keyed by param id (defined locally in SSE; in the source
// app this lived in a shared types module).
export type FilterParamValues = Record<string, number | boolean | string>;
