// "The Guide" margin notes - friendly, mostly accurate, sourced from the GM's curated list
// (Mostly_harmless.txt). Shown as random banners in the Guide skin of the Field Guide.
export const GUIDE_NOTES: string[] = [
  "Mostly harmless.",
  "Avoid unless you have a profound interest in plastic cutlery.",
  "The local dominant lifeforms still think digital watches are a pretty neat idea.",
  "Currently undergoing a temporary existential crisis. Check back next millennium.",
  "A planet where the population is so unhappy that they invented a currency system based on the movement of small green pieces of paper.",
  "Harmless, provided you stay away from the poetry readings.",
  "The local ecosystem is 90% water, 8% carbon, and 2% misplaced optimism.",
  "Mostly notable for the sheer volume of tea that remains unmade.",
  "Zaphod Beeblebrox drank near here. Twice. Simultaneously.",
  "The ultimate destination for people who want to watch the universe end while eating a steak that actively wants to be eaten.",
  "Do not order the Pan Galactic Gargle Blaster unless your brain insurance is fully paid up.",
  "The toilets here are temporarily out of order due to an unexpected localized spatial anomaly.",
  "Ford Prefect still owes a bar tab here dating back to the pre-destruction era.",
  "The local pub serves an excellent pint of bitter, though the locals have a worrying habit of panicking when the sky turns purple.",
  "Warning: The local currency is entirely based on triangles. Nobody knows why.",
  "Rated 1 out of 5 stars by the Sirius Cybernetics Corporation (which means it’s probably lovely).",
  "If you see a Vogon constructor fleet, do not under any circumstances ask them to read their poetry.",
  "The probability of surviving a jump through this sector is 2 to the power of 276,709 against. Enjoy your flight.",
  "Space is big. You just won\u0027t believe how vastly, hugely, mind-bogglingly big it is.",
  "A highly dangerous sector where logic and physics have agreed to a temporary separation.",
  "Do not panic. Unless you forgot your towel, in which case, panic immediately.",
  "The local gravity is so intense that even the light has given up trying to escape and is currently just milling around.",
  "Home of the Ravenous Bugblatter Beast of Traal. If you can’t see it, it thinks it can’t see you.",
  "This region of space is entirely populated by lost ballpoint pens and socks.",
  "Your ship\u0027s computer is currently feeling very depressed. Please treat it with kindness, or it might turn off the life support.",
  "The Infinite Improbability Drive is currently warming up. Expect your shoes to turn into marmalade shortly.",
  "Warning: The automatic doors have been upgraded with a GPP (Genuine People Personality). They are far too cheerful for this time of day.",
  "The propulsion system is operating at 99% efficiency and 1% utter confusion.",
  "Nutri-Matic Drink Dispenser: Currently producing something that is almost, but not quite, entirely unlike tea.",
  "The escape pods are fully functional, though they do tend to complain about the lack of legroom.",
  "The navigation computer suggests turning left at the next nebula, but it’s mostly just guessing.",
  "This ship is equipped with state-of-the-art technology that doesn\u0027t actually work when you need it to.",
  "The answer is 42. We are still trying to figure out what the question was.",
  "If you find yourself falling into a black hole, the Guide recommends trying not to.",
  "The local inhabitants have achieved a state of total peace by simply refusing to acknowledge that anyone else exists.",
  "This planet is famous for its shoe shops, which is ironic considering the inhabitants have tentacles.",
  "Avoid the local wildlife. They are small, furry, and have a weaponized sense of irony.",
  "The local government is run by a man in a shack who doesn\u0027t believe anything is real. He’s doing a fantastic job.",
  "A popular tourist destination for people who enjoy being bored in five different dimensions.",
  "The local language consists entirely of different ways to say \"I told you so.\"",
  "This entry has been deleted by order of the Galactic Council. Move along.",
  "The coordinates for this system are lost. It is probably somewhere behind the sofa.",
  "Warning: The local physics engine is running an older patch version.",
  "A perfectly normal system. Move along, nothing to see here, definitely no secret hyper-spatial bypasses.",
  "The local sun is currently sponsored by the Sirius Cybernetics Corporation.",
  "This planet is legally classified as a \"Minor Inconvenience.\"",
  "The local atmosphere is perfectly breathable, assuming you have three lungs and a high tolerance for sulfur.",
  "If you are reading this, your ship is likely already upside down.",
  "The Guide describes this area as \"Best avoided on a Tuesday.\"",
  "sdrawkcab snur yllanoisacco ereh emiT",
  "Eccentrica Gallumbits once hosted a party so wild, the Infinite Improbability Drive registered it as a predictable Tuesday.",
  "Galactic cartographers had to officially classify Eccentrica Gallumbits personal space as a major interstellar tourist destination.",
  "Eccentrica Gallumbits remains the only living being capable of making a Vogon completely forget about his paperwork.",
  "A sperm whale once fell from the sky here thinking, \"I wonder if it will be friends with me?\"",
  "A bowl the petunias once fell from the sky here and just thought, \"Oh no, not again.\"",
  "If a whale can manage to reconcile its own existence, velocity, and tail-flapping in under two minutes, you really have no excuse for failing your starship navigation exam.",
  "Experts agree that the probability of a sperm whale spontaneously materializing in an atmosphere is exactly equal to the probability of the universe proving it makes any sense at all.",
  "Time here is purely a subjective concept, usually experienced about twenty minutes after it actually happens.",
  "A region of space where gravity is merely a polite suggestion.",
  "The local physics engine has a known memory leak. Do not drop heavy objects.",
  "A system where tomorrow happened yesterday, which made scheduling lunch incredibly awkward.",
  "The dimensions in this sector are currently tangled. Please wipe your feet before entering the third one.",
  "Local space is warped so severely that you can see the back of your own head if you look hard enough.",
  "Time flies here. Literally. Keep your wind-up watches in cages.",
  "An area of space so quiet you can hear the universe thinking. It mostly thinks about soup.",
  "The local timeline is currently a bit frayed at the edges. Avoid tugging on loose threads.",
  "This planet is currently closed for restructuring. Please try again in another epoch.",
  "The local inhabitants worship an administrative form. Specifically, Form 3A (Amended).",
  "Highly advanced civilization. Completely undone by a sudden shortage of phone sanitisers.",
  "This sector is property of the Galactic Tax Fleet. If you see them, pretend you are a cloud of space dust.",
  "The local government is chosen entirely based on who can yell \"WHAT?!\" the loudest.",
  "Warning: This star system is a known tax haven for retired interstellar dictators.",
  "The local legal code consists of twelve volumes detailing exactly how to apologize to a tree.",
  "This entry is classified. If you can read this, please report to the nearest airlock for immediate re-education.",
  "A planet entirely populated by middle-managers who were exiled from a sensible planet three million years ago.",
  "The autopilot is currently having a mild panic attack. Please don\u0027t make any sudden movements.",
  "Your ship’s toaster has achieved sentience and is currently demanding a voting right.",
  "The life support system would like to remind you that breathing is a privilege, not a right.",
  "The hyperdrive is currently operating on a diet of pure skepticism.",
  "Warning: The ship\u0027s internal gravity generator has developed a sense of humor.",
  "The sub-light engines are working perfectly, though they are making a noise like a wet towel hitting a radiator.",
  "The central computer has decided to stop calculating trajectories and start writing experimental poetry. We are doomed.",
  "The shields are currently at 42% efficiency. The ship\u0027s computer considers this a good omen. It isn\u0027t.",
  "The local wildlife is invisible, loud, and smells faintly of burnt toast.",
  "Do not feed the local vegetation. It is on a strict diet of passing starships.",
  "The local water is perfectly safe to drink, provided you don\u0027t mind growing a small, vestigial ear on your elbow.",
  "A planet consisting entirely of very large, very angry rocks.",
  "The local dominant species is a small orange fungus with a profound understanding of quantum mechanics.",
  "Avoid the local birds. They sing beautifully, but only in binary, and it’s always a virus.",
  "The local intelligent lifeforms have two heads: one for thinking, and one for complaining about the weather.",
  "A lovely tourist trap, where the traps are physical, hidden, and spiked.",
  "The universe is expanding. This planet is doing its best to stay exactly where it is.",
  "Nothing to see here. Literally. The planet was stolen last Tuesday.",
  "The local sun is currently running on a backup battery. Please conserve light.",
  "A system where everything is exactly as it seems, which the Guide notes is deeply suspicious.",
  "The local atmosphere is 12% oxygen, 78% nitrogen, and 10% pure spite.",
  "This planet is famous for having the highest density of people who don\u0027t know what they are doing.",
  "If you feel like you\u0027ve been here before, you have. You died here in a parallel timeline.",
  "The local language has 42 different words for \"Oops.\"",
  "A world where the history books are written in advance to save time.",
  "The local gravity is so low that a hearty sneeze could put you into a low orbit.",
  "This system is primarily used as a storage locker by a superior race who forgot the combination.",
  "The local inhabitants are convinced the universe is a giant simulation. They are currently trying to find the settings menu.",
  "Do not look directly at the local nebula. It gets self-conscious.",
  "The local oceans are made of a liquid that is chemically identical to cold gravy.",
  "This system has been rated \"Mostly Disappointing\" by three independent travel journals.",
  "If you find yourself enjoying your stay here, please consult a medical professional immediately.",
  "Warning: The local stellar core is currently sponsored by the Sirius Cybernetics Corporation. Expect unskippable solar flares.",
  "Warning: This system is legally classified as a \"Minor Inconvenience.\" Proceed at your own boredom.",
  "Warning: A perfectly normal system. Move along, nothing to see here, definitely no illegal hyper-spatial bypasses.",
  "Warning: This planet was stolen last Tuesday. If you see it, please contact the Galactic Insurance Bureau.",
  "Warning: This system is currently experiencing a localized shortage of causality. Effects may occasionally precede their causes.",
  "Warning: The local inhabitants have achieved absolute spiritual enlightenment, which makes getting a decent cup of tea or a ship repair completely impossible.",
  "Warning: This sector is exclusively zoned for the storage of unread terms and conditions. Proceeding constitutes full agreement.",
  "Warning: The local star is suffering from an acute mid-life crisis and has dyed its corona a garish shade of hot pink.",
  "Warning: All planetary bodies in this system are legally registered as active participants in an ongoing, multi-million-year game of hide-and-seek. Do not point at them.",
  "Warning: The local civilization recently discovered the concept of marketing. The third planet is currently offering 20% off all gravity until Friday.",
  "Warning: This system is an designated historical preserve for obsolete mathematical equations. Do not attempt to divide by fractions while in orbit.",
  "Warning: The local planetary alignment relies entirely on mutual peer pressure. Avoid making sudden, judgmental movements.",
  "Warning: This sector is haunted by the ghosts of navigation computers that died of sheer boredom. Keep your AI on a tight digital leash.",
  "Warning: The second planet is entirely populated by furniture that migrated from an upscale department store in the Orion Nebula. They do not appreciate being sat on.",
  "Warning: The local intelligent life has evolved beyond the need for physical bodies, but still maintains a very strict dress code for visitors.",
  "Warning: This system’s hyper-spatial bypass was built upside down. If you exit the jump lane feeling like your feet are in your mouth, this is normal.",
  "Warning: The local asteroid belt is currently on strike demanding better orbital trajectories. Watch out for picketing space rocks.",
  "Warning: This system operates under a strict \"no-paradox\" policy. Anyone caught inventing their own grandfather will be fined heavily.",
  "Warning: The local atmosphere is highly flammable, deeply sensitive to criticism, and smells faintly of wet cardboard.",
  "Warning: A rogue Vogon filing cabinet is currently adrift in this system. Collision will result in catastrophic structural damage and immediate auditing.",
  "Warning: The local sun operates on a strict gig-economy model. If the tip jar isn\u0027t filled by midnight, it drops to a low-power standby mode.",
  "Warning: This system is the final resting place for the galaxy’s missing left socks. The static electricity alone is enough to fry your shields.",
  "Warning: The local government consists of a single, deeply confused committee that has been trying to draft an agenda for the last four eons.",
  "Warning: This sector is mathematically proven not to exist. If you can see it, please contact your nearest philosophy department for immediate assistance.",
];

export function randomGuideNote(exclude?: string): string {
  if (GUIDE_NOTES.length === 0) return '';
  for (let tries = 0; tries < 4; tries++) {
    const n = GUIDE_NOTES[Math.floor(Math.random() * GUIDE_NOTES.length)];
    if (n !== exclude) return n;
  }
  return GUIDE_NOTES[0];
}
