// Map a full-res planet-type image URL to its small WebP thumbnail.
//   /images/planet_types/web20ocean20planet.jpg  ->  /images/planet_types/thumbs/web20ocean20planet.webp
// Thumbs are pre-generated by scripts/gen-thumbs.cjs (128px, ~3-6 KB). Use this anywhere the image
// is shown small (the add-by-type picker); keep the original for the large body image.
// Anything that isn't a planet_types JPG/PNG is returned unchanged.
export function thumbUrl(url: string | undefined | null): string {
  if (!url) return '';
  const m = url.match(/^(.*\/planet_types)\/([^/]+)\.(jpe?g|png)$/i);
  if (!m) return url;
  return `${m[1]}/thumbs/${m[2]}.webp`;
}
